In [1]:
import numpy as np
print(np.__version__)

1.22.4


Create a NumPy array from a Python List

In [3]:
python_list = [num for num in range(1, 11)]

numpy_array = np.array(python_list)

print(numpy_array, type(numpy_array))

[ 1  2  3  4  5  6  7  8  9 10] <class 'numpy.ndarray'>


Array operations

In [4]:
#we can access elements of a numpy array the same way we do with list
print(numpy_array[3])

#to insert a new element we use the insert funciton that return the updated array
numpy_array = np.insert(numpy_array, 0, 5)
print(numpy_array)

4
[ 5  1  2  3  4  5  6  7  8  9 10]


Multidimentional arrays

In [14]:
#an array that contains arrays is a multidimentional array 
multidimentional_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float16)

print(multidimentional_array.dtype)
print(multidimentional_array.ndim)
print(multidimentional_array.shape)
print(multidimentional_array)

float16
2
(2, 3)
[[1. 2. 3.]
 [4. 5. 6.]]


In [7]:

#we can traverse a multidementional array using loops
for row in multidimentional_array:
    for item in row:
        print(item)

1
2
3
4
5
6


Array reshaping

In [18]:
#array reshaping is really useful when we are going to manipulate the data for example doing vector operations 
#we can do this using the reshape(function)

linear_array = np.array([num for num in range(2,9,2)])

#the linear array contains 4 elements so we could reshape it like (row-columns): 1-4 2-2 4-1

row_array = linear_array.reshape(1, 4)
matrix_array = linear_array.reshape(2, 2)
column_array = linear_array.reshape(4, 1)

print(row_array)
print(matrix_array)
print(column_array)

#if we dont want to manually calculate the dimention we can use the -1 as an argument
new_array = linear_array.reshape(2, -1)
#invalid_array = linear_array.reshape(3, -1)

print(new_array)
#print(invalid_array)

[[2 4 6 8]]
[[2 4]
 [6 8]]
[[2]
 [4]
 [6]
 [8]]
[[2 4]
 [6 8]]
